baseurl = "https://gilberto-sassi.github.io"
title = "Gilberto Pereira Sassi"

theme = "hugo-coder"

languagecode = "pt-br"
defaultcontentlanguage = "pt-br"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

[params]
    author = "Gilberto Pereira Sassi"
    description = "Personal webpage of Gilberto Pereira Sassi"
    keywords = "personal, blog, teacher, R, pytho, Rmarkdown "
    info = "Assistant Professor at Federal University of Bahia"
    avatarurl = "uploads/professor-antifa.jpeg"
    #gravatar = "john.doe@example.com"
    footercontent = "Paulista de berço e baiano por opção e coração."

    dateformat = "02/01/2006"

    hideFooter = true
    hideCredits = true
    hideCopyright = true
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
#     siteID = "ABCDE"
#     # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#     serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/gilberto-sassi/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab"
    weight = 2
    url = "https://gitlab.com/gilberto-sassi/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/gilberto_sassi/"
# [[params.social]]
#     name = "LinkedIn"
#     icon = "fab fa-linkedin"
#     weight = 4
#     url = "https://www.linkedin.com/in/johndoe/"
# [[params.social]]
#     name = "Medium"
#     icon = "fab fa-medium"
#     weight = 5
#     url = "https://medium.com/@johndoe"
# [[params.social]]
#     name = "RSS"
#     icon = "fas fa-rss"
#     weight = 6
#     url = "https://myhugosite.com/index.xml"
#     rel = "alternate"
#     type = "application/rss+xml"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Announcements"
            weight = 2
            url = "/announcements/"

            # [[languages.en.menu.main]]
            # name = "Regular Courses"
            # weight = 3
            # url = "/disciplinas/"

            [[languages.en.menu.main]]
            name = "Short Courses"
            weight = 4
            url = "/short code/"
            
            [[languages.en.menu.main]]
            name = "Projects"
            weight = 5
            url = "/projects/"

    [languages.pt-br]
        languagename = "Português"
        title = "Gilberto Pereira Sassi"

        [languages.pt-br.params]
            author = "Gilberto Pereira Sassi"
            info = "Professor da Universidade Federal da Bahia"
            description = "Página pessoal de Gilberto Pereira Sassi"
            keywords = "blog,desenvolvedor,pessoal"
            footercontent = "Coloque algum texto aqui."

        [languages.pt-br.menu]

            [[languages.pt-br.menu.main]]
            name = "Sobre mim"
            weight = 1
            url = "about/"

            [[languages.pt-br.menu.main]]
            name = "Avisos"
            weight = 2
            url = "/avisos/"

            [[languages.pt-br.menu.main]]
            name = "Disciplinas"
            weight = 3
            url = "/disciplinas/"

            [[languages.pt-br.menu.main]]
            name = "Minicursos"
            weight = 4
            url = "/minicursos/"

            [[languages.pt-br.menu.main]]
            name = "Pesquisa"
            weight = 5
            url = "/projetos/"

            # [[languages.pt-br.menu.main]]
            # name = "Contato"
            # weight = 6
            # url = "mailto:gilberto.sassi@ufba.br"

            